#pragma once

struct MESSAGE_AND_ID_ONLY { char id[12], command[4]; };
struct HANDSHAKE_SIGNAL_MESSAGE { char id[12], command[4], device_id[15], body[3]; };
struct CONTINUOUS_ANSWER_SETTING_ISOCHRONOUS_FEEDBACK_MESSAGE { char id[12], command[4], device_id[15], xxxxx[4], yy[2], zz[2]; };
struct LOGIN_MESSAGE { char id[12], command[4], device_id[15], body[60]; };
struct ALARM_MESSAGE { char id[12], command[4], device_id[15], body[60]; };
struct ANSWER_CALLING_MESSAGE { char id[12], command[4], body[60]; };
struct ISOCHRONOUS_FOR_CONTINUES_FEEDBACK_MESSAGE { char id[12], command[4], device_id[15], body[60]; };
struct CONTINUES_FEEDBACK_ENDING_MESSAGE { char id[12], command[4], body[60]; };
struct ANSWER_THE_RESTARTED_MESSAGE_OF_THE_DEVICE { char id[12], command[4], body[60]; };
struct SETUP_THE_SPEED_OF_THE_CAR { char id[12], command[4], body[60]; };
struct ANSWER_THE_SETTING_ACC_OPEN_SENDING_DATA_INTERVALS { char id[12], command[4]; };
struct CONTROL_CIRCUIT { char id[12], command[4], body[1]; };
struct CONTROL_OIL { char id[12], command[4], body[1]; };
struct ANSWER_THE_SETTING_GEOFENCE_MESSAGE { char id[12], command[4], body[1]; };
struct ANSWER_THE_SETTING_ACC_CLOSE_SENDING_DATA_INTERVALS { char id[12], command[4]; };

union data_payload_from_device
{
	struct MESSAGE_AND_ID_ONLY _MESSAGE_AND_ID_ONLY;
	struct HANDSHAKE_SIGNAL_MESSAGE _HANDSHAKE_SIGNAL_MESSAGE;
	struct CONTINUOUS_ANSWER_SETTING_ISOCHRONOUS_FEEDBACK_MESSAGE _CONTINUOUS_ANSWER_SETTING_ISOCHRONOUS_FEEDBACK_MESSAGE;
	struct LOGIN_MESSAGE _LOGIN_MESSAGE;
	struct ALARM_MESSAGE _ALARM_MESSAGE;
	struct ANSWER_CALLING_MESSAGE _ANSWER_CALLING_MESSAGE;
	struct ISOCHRONOUS_FOR_CONTINUES_FEEDBACK_MESSAGE _ISOCHRONOUS_FOR_CONTINUES_FEEDBACK_MESSAGE;
	struct CONTINUES_FEEDBACK_ENDING_MESSAGE _CONTINUES_FEEDBACK_ENDING_MESSAGE;
	struct ANSWER_THE_RESTARTED_MESSAGE_OF_THE_DEVICE _ANSWER_THE_RESTARTED_MESSAGE_OF_THE_DEVICE;
	struct SETUP_THE_SPEED_OF_THE_CAR _SETUP_THE_SPEED_OF_THE_CAR;
	struct ANSWER_THE_SETTING_ACC_OPEN_SENDING_DATA_INTERVALS _ANSWER_THE_SETTING_ACC_OPEN_SENDING_DATA_INTERVALS;
	struct CONTROL_CIRCUIT _CONTROL_CIRCUIT;
	struct CONTROL_OIL _CONTROL_OIL;
	struct ANSWER_THE_SETTING_GEOFENCE_MESSAGE _ANSWER_THE_SETTING_GEOFENCE_MESSAGE;
	struct ANSWER_THE_SETTING_ACC_CLOSE_SENDING_DATA_INTERVALS _ANSWER_THE_SETTING_ACC_CLOSE_SENDING_DATA_INTERVALS;
	unsigned char raw_data[1024];
};


